model: generator
model_dir: Model/generatorMVSEC.pth

gpu_ids: [1]
network:
    minimum_threshold: 0.01
    patch: 4
    use_log_images: true
    log_eps: 0.001
    log_threshold: 20
    clamp_num: 0.01
    gp_lambda: 1
    min_event_num: 10
    contrast_threshold_pos: 0.2
    contrast_threshold_neg: 0.2
    g_lr: 0.4
    d_lr: 0.4
    train_g_interval: 5
    reshape_size: [240, 304]
    bins: 10
    seq_len: 3
    size: [240, 304]
    uv_size: [1024,1024]
    data_size: 20
    debug: false
    output_rgb_path: output_data/RGB
    cell_size: 10
    if_binary: True


datasets:
  # train:
  #   name: cmu
  #   smpl_model_dir: body_models
  #   uv_obj_path: Data/smpl_uv.obj
  #   original_uv_img: Data/smpl_uv.png
  #   #data_simu: /home/lgx/data/whitebox_attack/train/
  #   data_simu_pose: /home/lgx/data/whitebox_attack_cmupose/whitebox_attack/train/
  #   labeled_simu_pose: /home/lgx/data/whitebox_attack_cmupose/whitebox_attack_labels
    
  #   bins: 10
  #   seq_len: 3
  #   size: [240, 304]
  #   uv_size: [1024,1024]
  #   size: [240, 304]
  #   uv_size: [1024,1024]
  #   debug: false
  #   dl: 0
  #   dr: 281
  #   data_size: 20
  #   save_dir: ./Model/TrainingModels/23/
  #   tb_path: ./Model/TrainingModels/23/
  #   mask_path: utils/sam_mask
  #   mask_part: ['upper_body','legs','hands'] #['head','upper_body','leg','hand','fingers','feet']
  #   cell_size: 50
  #   #num_epochs: 100000
  #   num_workers: 0
  #   batch_size: 1
  #   d_batch_size: 256
  #   epoch_save: 5
  #   show_interval: 1
  #   steps_loss: 20
  #   warmup: 0
  #   lr_end: 1e-2
  #   trainstep: 100
  #   minimum_threshold: 0.01
  #   patch: 4
  #   use_log_images: true
  #   # log_eps: 0.001
  #   log_threshold: 20
    # clamp_num: 0.01
    # gp_lambda: 1
    # min_event_num: 10
  val:
    name: cmu
    reshape_size: [240, 304]
    bins: 10
    
    seq_len: 3
    smpl_model_dir: body_models
    uv_obj_path: Data/smpl_uv.obj
    original_uv_img: Data/smpl_uv.png
    #data_simu: /home/lgx/data/whitebox_attack/train/
    data_simu_pose: /home/lgx/data/whitebox_attack_cmupose/whitebox_attack/test/
    labeled_simu_pose: /home/lgx/data/whitebox_attack_cmupose/whitebox_attack_labels
    mask_path: utils/sam_mask
    mask_part: ['upper_body','legs','hands'] #['head','upper_body','leg','hand','finger','foot']
    cell_size: 10

    size: [240, 304]
    uv_size: [1024,1024]
    debug: false
    dl: 0
    dr: 281
    data_size: 20
    save_dir: ./Model/TrainingModels/23/
    tb_path: ./Model/TrainingModels/23/
    output_rgb_path: output_data/RGB
    contrast_threshold_pos: 0.2
    contrast_threshold_neg: 0.2
    g_lr: 0.4
    d_lr: 0.4
    train_g_interval: 5
    # num_epochs: 100000
    num_workers: 0
    batch_size: 1
    d_batch_size: 256
    epoch_save: 5
    show_interval: 1
    steps_loss: 20
    warmup: 0
    lr_end: 1e-2
    trainstep: 100
    minimum_threshold: 0.01
    patch: 4
    use_log_images: true
    log_eps: 0.001
    log_threshold: 20
    clamp_num: 0.01
    gp_lambda: 1
    min_event_num: 10
    metrics:  ['seq_attack_success_rate'] #['AP'] #['seq_attack_success_rate','avg_attack_success_rate']


path:
  pretrain_model_G: checkpoints/best.pth
  #pretrain_model_G: ~ #output/saved_checkpoints/530000_G.pth  #~ #lgx
  strict_load: true #true 
  resume_state: ~ #output/saved_checkpoints/11500.state #~ #lgx
  models: output/saved_checkpoints/ #/home/abcd233746pc/VideoINR-Continuous-Space-Time-Super-Resolution/saved_checkpoints/Ours_noT_N3_1106/
  training_state: output/saved_checkpoints/ #/home/abcd233746pc/VideoINR-Continuous-Space-Time-Super-Resolution/saved_checkpoints/Ours_noT_N3_1106/
  attacked_uv_texture: output/uv_texture/
  root: output/
  log: output/
  experiments_root: output/



logger:
  print_freq: 10
  save_checkpoint_freq: !!float 1000

val:
  val_freq: !!float 1000
  save_img: false

train:
  lr_G: !!float 1e-4 
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 15000
  warmup_iter: -1 #4000  # -1: no warm up
  T_period: [15000, 15000, 15000, 15000]
  restarts: [15000, 30000, 60000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  
  lambda: 10000
  #val_freq: !!float 20

is_train: True

